### ISSUE TITLE
'type' is a reserved word

### ISSUE THREAD

**Issue by alinz** [trenskow/isvalid-express.js#1]
Thanks for interesting project.
I have started using it in one of my project and I notice that if I my json contains "type" as a key, the validation fails. I digged into it and found that isvalid is using "type" internally. How can I bypass that?

**Comment by trenskow** [comment]
Sorry, I did not see this issue before now. If it is still an issue - and you haven't found some other solution, the solution is to explicitly define an object.

So instead of

   {

**Comment by trenskow** [comment]
Sorry, I did not see this issue before now. If it is still an issue - and you haven't found some other solution, the solution is to explicitly define an object.

So instead of

```
{
    type: { type: String }
}
```

you would do

```
{
    type: Object,
    schema: {
        type: { type: String }
    }
}
```

**Comment by alinz** [comment]
Thanks @trenskow. Your library was an inspiration to make [simple-json-validator](https://github.com/alinz/simple-json-validator). I have been using that in my code base. Thanks

**Comment by trenskow** [comment]
Cool! Happy to have been an inspiration :+1: :)
